--Insert values in MEAL_CHOICE Table
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000001','cookie_tray','reg_snack');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000002','veggie_tray','heath_snack');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000003','Pork_withpotatoes and vegetables','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000004','Pork with species','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000005','Pork champion sauce','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000006','Pork loin in plum sauce','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000007','Pork medallions in mustard sauce','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000008','Pork medallions in gravy sauce','pork');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000009','Shrimp  stuffed with coconut in creamy rice and vegetables','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000010','shrimp in spinach sauce, potato and vegetable lasagna','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000011','Grilled shrimp with spaghett and vegetables','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000012','Shrimp stuffed with marlin and cheese','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000013','fish combination with garlic and shrip in tropical fruit sauce','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000014','Fish fillet in spinach sauce with creamy risotto and vegetable','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000015','Fish Fillet with creamy rice and vegetables in marinade sauce','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000016','Salmon fillet with potato and vegetable pure','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000017','Salmon fillet to the menier with rice and vegetables','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000018','Atun medallon with rice and vegetables','fish');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000019','shrimp stuffed with jaiba wrapped in procciuto with potato pure and vegetables','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000020','Beef scalps in balsamic sauce','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000021','Beef scalps in red wine','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000022','Beef fillet in mustard sauce','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000023','Beef fillet in red wine sauce','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000024','Mozarela and spinach cheese beef fillet with gravy sauce and potato pure accompanied with ski','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000025','Beef steak on roasted portobello and mozarela cheese with creamy rice and olive sauce','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000026','Wellington fillet in cheese sauce and vegetables','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000027','beef scalop in purple onion sauce','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000028','beef fillet sealed to fine herbs with Platan','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000029','beef fillet medallon in pepper sauce and vegetables','beef');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000030','White wine chicken medallions with grapes with potato and vegetable potato pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000031','Chicken medallions in mashroom sauce with potato and brocoli pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000032','Chicken medallions in red wine with vegetables and potatoes','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000033','Chicken thighs in hot sauce with creamy rice and vegetables','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000034','Mediterranean chicken thighs  with potato pure and vegetables','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000035','Parmesan chicken breast in tomato sauce with vegetable pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000036','Chicken breast stuffed with mashrooms with rustic vegetables and potato pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000037','Chicken breast stuffed with cheese with potato and brocoli pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000038','Supreme chicken stuffed with chipotle sauce with creamy rice and vegetable ratatouille','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000039','Supreme chicken  in poblana sauce with potato and vegetable pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000040','Supreme chicken stuffed with spinach with potato and brocoli puree with vegetables','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000041','Supreme chicken stuffed with ham and cheese in mushroom sauce with potato and vegetable pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000042','Supreme chicken stuffed with  Jalapeno sauce  with potato and vegetable pure','chicken');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000043','Mexican eggs with beans and roasted nopal','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000044','Eggs with chicken in poblano chili sauce','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000045','Eggs with chicken and pepper','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000046','Potato and sausage Spanish cake','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000047','Omette with shrip and Cheese','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000048','Omelette with ham and cheese','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000049','Omelette of whites filled with cheese and spinach','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000050','Omelette with veggies and cheese','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000051','Omette with cheese only','breakfast');
INSERT INTO FALL22_004_6_MEAL_CHOICE(FM_NUM, MEAL_NAME, MEAL_TYPE) VALUES('2000052','Omelette with poblano peppers and mozarela','breakfast');
 
