INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C001','Corporate','123 Creeck Rd, Mansfield, TX','abc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C002','Corporate','133 Greeck Rd, Allen, TX','bcc@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C003','Corporate','433 Ceedck Rd, Arlington, TX','cbc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C004','Corporate','543 Creeck Rd, Allen, TX','dbc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C005','Corporate','323 Creeck Rd, Mansfield, TX','ebc@gmail.com','social media','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C006','Corporate','153 Creeck Rd, Mansfield, TX','fbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C007','Corporate','173 Creeck Rd, Allen, TX','gbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C008','Corporate','193 Creeck Rd, Mansfield, TX','hbc@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C009','Corporate','133 Creeck Rd, Mansfield, TX','ibc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C010','Corporate','223 Creeck Rd, Mansfield, TX','jbc@gmail.com','social media','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C011','Corporate','323 Creeck Rd, Allen, TX','kbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C012','Corporate','423 Creeck Rd, Mansfield, TX','lbc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C013','Corporate','523 Creeck Rd, Mansfield, TX','mbc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C014','Corporate','623 Creeck Rd, Alrington, TX','nbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C015','Corporate','723 Creeck Rd, Mansfield, TX','obc@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C016','Corporate','823 Creeck Rd, Allen, TX','pbc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C017','Corporate','923 Creeck Rd, Mansfield, TX','qbc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C018','Corporate','113 Creeck Rd, Allen, TX','rbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C019','Corporate','143 Creeck Rd, Mansfield, TX','sbc@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C020','Corporate','183 Creeck Rd, Mansfield, TX','tbc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C021','Corporate','103 Creeck Rd, Mansfield, TX','ubc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C022','Corporate','121 Creeck Rd, Dallas, TX','vbc@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C023','Corporate','122 Creeck Rd, Allen, TX','xbc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C024','Corporate','124 Creeck Rd, Mansfield, TX','ybc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C025','Corporate','129 Creeck Rd, Mansfield, TX','zbc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C026','Corporate','183 Creeck Rd, Mansfield, TX','aac@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C027','Corporate','523 Creeck Rd, Dallas, TX','acc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C028','Corporate','563 Creeck Rd, Mansfield, TX','adc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C029','Corporate','873 Creeck Rd, Mansfield, TX','aec@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C030','Corporate','983 Creeck Rd, Haltom City, TX','afc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C031','Corporate','533 Creeck Rd, Mansfield, TX','agc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C032','Corporate','233 Creeck Rd, Mansfield, TX','ahc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C033','Corporate','167 Creeck Rd, Mansfield, TX','aic@gmail.com','social media','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C034','Corporate','168 Creeck Rd, Haltom City, TX','ajc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C035','Corporate','169 Creeck Rd, Mansfield, TX','akc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C036','Corporate','170 Creeck Rd, Mansfield, TX','alc@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C037','Corporate','171 Creeck Rd, Coppel, TX','amc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C038','Corporate','172 Creeck Rd, Mansfield, TX','anc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C039','Corporate','173 Creeck Rd, Mansfield, TX','aoc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C040','Corporate','174 Creeck Rd, Haltom City, TX','apc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C041','Corporate','175 Creeck Rd, Mansfield, TX','aqc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C042','Corporate','176 Creeck Rd, Haltom City, TX','arc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C043','Corporate','177 Creeck Rd, Coppel, TX','asc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C044','Corporate','178 Creeck Rd, Mansfield, TX','atc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C045','Corporate','179 Creeck Rd, Arlington, TX','auc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C046','Corporate','193 Creeck Rd, Mansfield, TX','avc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C047','Corporate','194 Creeck Rd, Coppel, TX','axc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C048','Corporate','195 Creeck Rd, Mansfield, TX','ayc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C049','Corporate','196 Creeck Rd, Mansfield, TX','azc@gmail.com','social media','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C050','Corporate','197 Creeck Rd, Coppel, TX','bcc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C051','Individual','993 Creeck Rd, Mansfield, TX','aba@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C052','Individual','994 Greeck Rd, Allen, TX','bcb@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C053','Individual','996 Ceedck Rd, Arlington, TX','ckc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C054','Individual','997 Creeck Rd, Allen, TX','dbd@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C055','Individual','998 Creeck Rd, Mansfield, TX','ebe@gmail.com','social media','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C056','Individual','884 Creeck Rd, Mansfield, TX','fbf@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C057','Individual','885 Creeck Rd, Allen, TX','gbg@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C058','Individual','886 Creeck Rd, Mansfield, TX','hbh@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C059','Individual','887 Creeck Rd, Mansfield, TX','ibi@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C060','Individual','888 Creeck Rd, Mansfield, TX','jbj@gmail.com','social media','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C061','Individual','673 Creeck Rd, Allen, TX','kbk@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C062','Individual','674 Creeck Rd, Mansfield, TX','lbl@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C063','Individual','675 Creeck Rd, Mansfield, TX','mbm@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C064','Individual','678 Creeck Rd, Alrington, TX','nbn@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C065','Individual','679 Creeck Rd, Mansfield, TX','obo@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C066','Individual','680 Creeck Rd, Allen, TX','pbp@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C067','Individual','681 Creeck Rd, Mansfield, TX','qbq@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C068','Individual','682 Creeck Rd, Allen, TX','rbr@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C069','Individual','683 Creeck Rd, Mansfield, TX','sbs@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C070','Individual','684 Creeck Rd, Mansfield, TX','tbt@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C071','Individual','685 Creeck Rd, Mansfield, TX','ubu@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C072','Individual','686 Creeck Rd, Dallas, TX','vbv@gmail.com','social media','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C073','Individual','687 Creeck Rd, Allen, TX','xbx@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C074','Individual','724 Creeck Rd, Mansfield, TX','ybksc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C075','Individual','729 Creeck Rd, Mansfield, TX','zbcds@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C076','Individual','783 Creeck Rd, Mansfield, TX','aadsc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C077','Individual','523 Creeck Rd, Dallas, TX','accs@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C078','Individual','533 Creeck Rd, Mansfield, TX','adsdc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C079','Individual','543 Creeck Rd, Mansfield, TX','aetyc@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C080','Individual','553 Creeck Rd, Haltom City, TX','awefc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C081','Individual','563 Creeck Rd, Mansfield, TX','arggc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C082','Individual','573 Creeck Rd, Mansfield, TX','ahhyc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C083','Individual','587 Creeck Rd, Mansfield, TX','aigfc@gmail.com','social media','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C084','Individual','598 Creeck Rd, Haltom City, TX','ajgrc@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C085','Individual','609 Creeck Rd, Mansfield, TX','adkc@gmail.com','friend','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C086','Individual','670 Creeck Rd, Mansfield, TX','atylc@gmail.com','internet','email');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C087','Individual','161 Creeck Rd, Coppel, TX','amikc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C088','Individual','776 Creeck Rd, Mansfield, TX','anujc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C089','Individual','786 Creeck Rd, Mansfield, TX','agoc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C090','Individual','444 Creeck Rd, Haltom City, TX','adspc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C091','Individual','666 Creeck Rd, Mansfield, TX','adqc@gmail.com','internet','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C092','Individual','777 Creeck Rd, Haltom City, TX','arasc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C093','Individual','888 Creeck Rd, Coppel, TX','afdsc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C094','Individual','999 Creeck Rd, Mansfield, TX','atfdc@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C095','Individual','111 Creeck Rd, Arlington, TX','aucd@gmail.com','friend','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C096','Individual','112 Creeck Rd, Mansfield, TX','avcfrsd@gmail.com','internet','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C097','Individual','113 Creeck Rd, Coppel, TX','axc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C098','Individual','114 Creeck Rd, Mansfield, TX','ayc@gmail.com','friend','phone');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C099','Individual','115 Creeck Rd, Mansfield, TX','aztgc@gmail.com','social media','walk-in');
INSERT INTO FALL22_004_6_CLIENT (CLIENT_ID, C_type, C_address, C_email, way_met_center, way_of_contact) VALUES ('C100','Individual','117 Creeck Rd, Coppel, TX','bcdvc@gmail.com','friend','walk-in');



